name: CI
on: [pull_request]

jobs:
  ci-image:
    name: Build CI image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Remove dockerignore
        run: |
          rm .dockerignore
      - name: Build and push Docker images
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: "jurre/dependabot-core-ci"
          dockerfile: "Dockerfile.ci"
          image_tag: ${{ github.sha }}
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run Rubocop linting
        run: |
          cd /home/dependabot/dependabot-core && rake ci:rubocop

  bundler:
    name: Bundler
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run bundler tests
        run: |
          cd /home/dependabot/dependabot-core/bundler && bundle exec rspec spec

  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run cargo tests
        run: |
          cd /home/dependabot/dependabot-core/cargo && bundle exec rspec spec

  common:
    name: Common
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run common tests
        run: |
          cd /home/dependabot/dependabot-core/common && bundle exec rspec spec

  composer:
    name: Composer
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run composer tests
        run: |
          cd /home/dependabot/dependabot-core/composer && bundle exec rspec spec

  dep:
    name: Dep
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run dep tests
        run: |
          cd /home/dependabot/dependabot-core/dep && bundle exec rspec spec

  docker:
    name: Docker
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run docker tests
        run: |
          cd /home/dependabot/dependabot-core/docker && bundle exec rspec spec

  elm:
    name: Elm
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run elm tests
        run: |
          cd /home/dependabot/dependabot-core/elm && bundle exec rspec spec

  git-submodules:
    name: Git submodules
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run git submodules tests
        run: |
          cd /home/dependabot/dependabot-core/git_submodules && bundle exec rspec spec

  go-modules:
    name: Go modules
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run go modules tests
        run: |
          cd /home/dependabot/dependabot-core/go_modules && bundle exec rspec spec

  gradle:
    name: Gradle
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run gradle tests
        run: |
          cd /home/dependabot/dependabot-core/gradle && bundle exec rspec spec

  hex:
    name: Hex
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run hex tests
        run: |
          cd /home/dependabot/dependabot-core/hex && bundle exec rspec spec

  maven:
    name: Maven
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run maven tests
        run: |
          cd /home/dependabot/dependabot-core/maven && bundle exec rspec spec

  npm-and-yarn:
    name: npm and yarn
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run npn and yarn tests
        run: |
          cd /home/dependabot/dependabot-core/npm_and_yarn && bundle exec rspec spec

  nuget:
    name: Nuget
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run nuget tests
        run: |
          cd /home/dependabot/dependabot-core/nuget && bundle exec rspec spec

  omnibus:
    name: Omnibus
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run omnibus tests
        run: |
          cd /home/dependabot/dependabot-core/omnibus && bundle exec rspec spec

  python:
    name: Python
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run python tests
        run: |
          cd /home/dependabot/dependabot-core/python && bundle exec rspec spec

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    container: jurre/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    steps:
      - name: Run terraform tests
        run: |
          cd /home/dependabot/dependabot-core/terraform && bundle exec rspec spec
